### ISSUE TITLE
soundtest

### ISSUE THREAD

**Issue by Phosphate5** [angstsmurf/soundtest#4]
Hi. 

Im using sounds in inform7 and found your site. I downloaded and tried Sound test.inform, and got the following error after  running Autotest.. and then the line When the AIFF stops playing. 

Fatal error: Printing text to a window that is waiting for line or character input is not allowed. 

I thought you might want to fix it.
Greetings  and and a happy new year
Michelle

**Comment by angstsmurf** [comment]
Hi, thanks for reporting this, and the same to you! Good to hear that someone is actually interested in this. May I ask which interpreter you are using? Did you cancel out of any test with Escape? I'm afraid I can't seem to reproduce it here.

**Comment by angstsmurf** [comment]
Should be fixed by ad6376f.
