### ISSUE TITLE
Request: Add playing-on-paused-channel test

### ISSUE THREAD

**Issue by townba** [angstsmurf/soundtest#5]
It’d be great if this included a playing-on-paused-channel test. According to [Glk spec §8.3](https://www.eblong.com/zarf/glk/glk-spec-075_8.html#s.3), “You can also play a sound on a paused channel; the sound is paused immediately, and does not progress.”

**Comment by angstsmurf** [comment]
This can in theory be done already with PAUSE, PLAY, UNPAUSE, although it seems to reveal a bug in Spatterlight and Gargoyle where a channel is sometimes reported as not paused even when it should be. This needs to be investigated further.

Of course, a dedicated test for this in the automatic testing suite would be nice as well.

**Comment by townba** [comment]
It may be an issue with the test itself thinking the channel is no longer paused. (I don't know of a Glk function to report whether or not a channel is paused.)

With the PAUSE/PLAY/UNPAUSE sequence, it's not calling `glk_schannel_unpause` as I would expect:

```
>pause
Channel 1 paused.

>play
You push the play button. Sound channel 1 begins to play the AIFF at volume
65536 with 1 repetition and notification number 1.

>unpause
Current sound channel is not paused.

>
```

When I hack the test to make the calls to `glk_schannel_pause`, `glk_schannel_play`, and `glk_schannel_unpause` manually, it works as I expect.

**Comment by angstsmurf** [comment]
Yes, you are right. I wasn't reading my code properly. I think that 9391d45 takes care of this.

**Comment by angstsmurf** [comment]
I added testing of this to the automated tests (the pause test, the multi test and the fade test, specifically) in 3433222. A minor test of this was already included in the pause test, but doing it more thoroughly doesn't hurt.

Thanks for the suggestion! It made me notice and fix quite a number of bugs.

**Comment by angstsmurf** [comment]
By the way, the paused channel behaviour is still wrong when using glk_schannel_play_multi(). It should not automatically unpause channels. I'll fix that tomorrow.

**Comment by angstsmurf** [comment]
Now this hopefully works as it should. Thanks again! Don't hesitate to report any other bugs, comments or feature requests.

**Comment by townba** [comment]
Awesome! Thank you!
