### ISSUE TITLE
Allow setting volume more than 65536

### ISSUE THREAD

**Issue by curiousdannii** [angstsmurf/soundtest#7]
Glk allows for overdriving the volume.

**Comment by angstsmurf** [comment]
This is [briefly tested in the auto test suite](https://github.com/angstsmurf/soundtest/blob/7634d0091fd78669a5c5343800da07165b96ecfa/Soundtest.inform/Source/story.ni#L1358-L1364), but I agree that it would be nice to be able to do it in the "playground" as well. (Insert tired Spinal Tap joke here.)

**Comment by angstsmurf** [comment]
After [858a277](https://github.com/angstsmurf/soundtest/commit/858a2771d85b75e052d7e3a1726708cc5ff31894), it is now possible to set the volume to any positive number up to 2147483647. This is currently an undocumented feature, not reflected in any descriptions or messages.
